name: Setup Server

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup VPS LAMP Stack
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo apt update -y

            # --- NGINX ---
            if ! command -v nginx &>/dev/null; then
              echo "[+] Install Nginx"
              sudo apt install -y nginx
            else
              echo "[=] Nginx sudah terpasang"
            fi

            # --- PHP 8.3 + FPM ---
            if ! php -v | grep -q "8.3"; then
              echo "[+] Install PHP 8.3 dan FPM"
              sudo add-apt-repository -y ppa:ondrej/php
              sudo apt update
              sudo apt install -y php8.3 php8.3-fpm
            else
              echo "[=] PHP 8.3 sudah terpasang"
            fi

            # --- PHP Extensions ---
            echo "[+] Install PHP extensions"
            sudo apt install -y php8.3-{cli,common,gd,mysql,xml,mbstring,curl,zip,bcmath,intl,soap,imagick,readline}

            # --- MariaDB ---
            if ! command -v mariadb &>/dev/null; then
              echo "[+] Install MariaDB"
              sudo apt install -y mariadb-server
              sudo systemctl enable mariadb
              sudo systemctl start mariadb
            else
              echo "[=] MariaDB sudah terpasang"
            fi

            echo "[✔] Setup selesai!"
